name: Android CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      -main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleRelease && find app/build/outputs
    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-armeabi-v7a-release-unsigned.apk
        path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

